name: tigtesting
favicon: null
layout_spectrum: 0.49514
typography_spectrum: 0.48633
title: Just playing around with Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8caac6'
    - '#bd7756'
    - '#2d73be'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
