name: tigtesting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6966496431268752
title: Just playing around with Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff9a00'
    - '#34caeb'
    - '#a73f00'
    - '#b90025'
    - '#697773'
  brandStrength: 1
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
