name: tigtesting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6966496431268752
title: Just playing around with Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#60387f'
    - '#fffed8'
    - '#fe7be1'
    - '#db1815'
    - '#44fe41'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
