name: tigtesting
favicon: null
layout_spectrum: 0.6097326287999749
typography_spectrum: 0.6966496431268752
title: Just playing around with Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8729877942241728
  lightness: 0.26448714593425393
  saturation: 0.09725654334761202
  rhythmicContrast: 0.018170340452343225
purpose: []
